### ISSUE TITLE
Known Unsupported Operations

### ISSUE THREAD

**Issue by belldandyxtq** [pfnet/pfio#109]
- numpy (On HDFS)
    1. [tofile](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.tofile.html)
    2. [fromfile](https://docs.scipy.org/doc/numpy/reference/generated/numpy.fromfile.html)
    3.  [save](https://docs.scipy.org/doc/numpy/reference/generated/numpy.save.html#numpy-save)
    4. [load](https://docs.scipy.org/doc/numpy/reference/generated/numpy.load.html#numpy-load)
The issue is caused by missing `fileno` when using HDFS in `tofile` and `fromfile`. `save` and `load` call `tofile` and `fromfile` internally. 
However, `savez` and `loadz` are fine to use since they use a `zip` wrapper.

**Comment by kuenishi** [comment]
I understand those cases are not supported, but I also think it's a little out of the scope of this library, possibly because NumPy requires direct access to file discriptors. We won't simulate the behaviour of file descriptors.
