### ISSUE TITLE
Consider to remove krbticket

### ISSUE THREAD

**Issue by ksauzz** [pfnet/pfio#124]
krbticket was introduced for updating kerberos ticket periodically, but I noticed hdfs java client also has [the similar functionality](https://github.com/apache/hadoop/blob/branch-3.2.1/hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/security/UserGroupInformation.java#L844-L849). It seems krbticket is no longer needed.

Note that hdfs client can use other environment variables to specify [keytab, ccache path, and principal](https://github.com/apache/hadoop/blob/branch-3.2.1/hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/security/UserGroupInformation.java#L1880-L1887). It's available in 3.0 releases or later.

**Comment by belldandyxtq** [comment]
Done
