### ISSUE TITLE
Add chmod

### ISSUE THREAD

**Issue by belldandyxtq** [pfnet/pfio#137]
We want to add `chmod` to support mode setting

**Comment by kuenishi** [comment]
I'm declined to add chmod.
We'll need more broad permission system that cover wider use cases. `chmod` is not common among cloud storage systems such as S3 and Google CS. The POSIX-style authorization system is too naive, and I don't think it's majority. Hadoop also has ACL-style feature, which is superset of POSIX-style permission model.
