### ISSUE TITLE
Expose PosixFileSystem in the document

### ISSUE THREAD

**Issue by belltailjp** [pfnet/pfio#140]
In the purpose of filesystem/container abstraction, it is a common idiom for pfio:
```python
if path.endswith('.zip'):
    fs = pfio.open_as_container(path)
else:
    fs = pfio
    pfio.set_root(path)    # <--- In some cases (especially when abstracting zip and filesystem) we need this.
```
However `pfio.set_root` changes the global state and thus sometimes it may be troublesome.
`fs = PosixFileSystem(root='/path/to/dir')` is better use to solve this issue.
The small problem here is that currently `PosixFileSystem` is only used internally, it's not documented and we need to specify the fully qualified path to use this class (`pfio.filesystems.posix.PosixFileSystem`).

I'd like this class to be documented and can be accessed directly under the `pfio` module.

Another approach to realize the same thing is to support POSIX/HDFS directory in `open_as_container`, which would internally behave the same (makes `PosixFileSystem` object with root).

**Comment by kuenishi** [comment]
Closing in favor of v2 API. Also, `class Local` will be documented and it supports chroot-like behaviour..
