### ISSUE TITLE
Support PPE profiling

### ISSUE THREAD

**Issue by kuenishi** [pfnet/pfio#258]
One of requirements in our systems is to be suitable with other tools. As PPE has now Profiling feature, it would be nice if PFIO rides on its use cases, rather than inventing its own.

c.f. https://github.com/pfnet/pytorch-pfn-extras/pull/144

Update: PPE and PyTorch are both not ready for 3.10. https://github.com/pfnet/pytorch-pfn-extras/issues/386

Target tasks:
- [x] Local #326 / #340 
- [x] S3 #341 
- [x] Zip #344
- [x] CachedHttpFs #356 
- [x] FileCache / multiprocess FileCache #350 
- [x] HttpCache #356 
- [x] Add test suite with/without PPE

**Comment by kuenishi** [comment]
Approach:
- Put PPE's decorator onto PFIO
- Check if we can get stats by adding current decorator
- Check the chrome tracing in outdir once PPE emit happened: c.f. https://github.com/pfnet/pytorch-pfn-extras/issues/729
- Save the start/end timing as trace with PPE

**Comment by k5342** [comment]
All milestones are now completed 🎉
Thank you for working hard with us and your contribution, @KantaTamura!

**Comment by kuenishi** [comment]
So it's now ready to ship :congratulations: . It'll be included in 2.9.0 release as the key feature of the new release.
