### ISSUE TITLE
Design of ChainerIO profiler

### ISSUE THREAD

**Issue by belldandyxtq** [pfnet/pfio#29]
Memo for the requirements
1. Plug-in like => can switch between different profilers, or customize profilers, e.g. record fields
2. Separate log writers to switch formats
3. Being able to profile a certain block of code
4. Being able to turn on/off at run time

**Comment by kuenishi** [comment]
I'd suggest more requirements for further discussions in future:

- Any realistic use cases, with problem to be solved
- Good combination of existing profiling frameworks or systems

**Comment by kuenishi** [comment]
Won't work on it so far in favor of https://github.com/pfnet/pfio/issues/258 .
