### ISSUE TITLE
Use configure instead of global variables for default context

### ISSUE THREAD

**Issue by belldandyxtq** [pfnet/pfio#59]
The default context currently is implemented with a few raw global variables. Such implementation cause many troubles, e.g. difficult to switch and keep everything in consistent and no support for context manager for local configure. We need to use the configuration like the one in [Chainer](https://github.com/chainer/chainer/blob/master/chainer/configuration.py).

**Comment by kuenishi** [comment]
Closing in favor of v2 API.
