### ISSUE TITLE
Check for supported scheme in `create_handler`

### ISSUE THREAD

**Issue by belldandyxtq** [pfnet/pfio#86]
**Problem**
We need to check if the given scheme is supported or not, which is not done currently

**Example**
```
# 'boo' is not a supported scheme
# The call returns h1 as a POSIX (default) handler
# and the root is set to "boo"
>>> h1 = chainerio.create_handler('boo')
>>> h1
<chainerio.filesystems.posix.PosixFileSystem object at 0x2b2848e58eb8>
>>> print(h1.root)
boo
```

**Comment by belldandyxtq** [comment]
It seems other APIs do not have this issue as they accept the UNIX-like path as well as the scheme, and 'boo' will be treated as a UNIX-like path.

**Comment by kuenishi** [comment]
Reopen as #88 is just a workaround. [Discussion](https://github.com/chainer/chainerio/pull/88#issuecomment-558060815) should be continued here.

**Comment by belldandyxtq** [comment]
>The argument of create_handler(scheme) is kind of misleading, as other functions and methods take URI as arguments. That said, more intuitive improvement would be to let it accept full or partial URI and make .root member configurable and effective.

I think this is a good solution to me, which can be the backend of `set_root`

>Also we have to support choosing HDFS-cluster at each handler, which is currently not available.

This would involves two ToDos:
1. Switching between HDFS-cluster would involve switching the connection. Or we can maintains connections to all the available clusters in hdfs.xml.
2. Differentiating the cluster-name from directories

**Comment by belldandyxtq** [comment]
@kuenishi What do you think about this

**Comment by kuenishi** [comment]
My suggestion is to change argument of `create_handler` from just a scheme to [full URI](https://tools.ietf.org/html/rfc3986) that indicates some directory in some cluster, or in local filesystem. This change involves a lot of code change like you suggested, and maybe to support creating handlers like chdir-like style. Not only about full URI but relative URI or pathnames are to be in discussion scope.
