### ISSUE TITLE
Some global functions do not follow the `set_root`

### ISSUE THREAD

**Issue by belldandyxtq** [pfnet/pfio#98]
**Problems**
A few `chainer.xxx` functions (e.g. `chainerio.exists`) do not  follow the `set_root`.

**How to reproduce**
```
 hdfs dfs -ls /home/
ls: `/home/': No such file or directory
$ python
Python 3.6.8 (default, Oct  7 2019, 09:28:08)                
[GCC 7.4.0] on linux                                                                                                                                          
Type "help", "copyright", "credits" or "license" for more information.      
>>> import chainerio
>>> chainerio.set_root("hdfs")
>>> chainerio.exists("/home/")
True
```
**Cause**
These functions are calling an old function which ignores the `default_handler`
https://github.com/chainer/chainerio/blob/ca79de952f21cc216cc70c1a0b87afd6d07426cd/chainerio/__init__.py#L267
https://github.com/chainer/chainerio/blob/ca79de952f21cc216cc70c1a0b87afd6d07426cd/chainerio/__init__.py#L43

**Comment by kuenishi** [comment]
Closing in favor of v2 API.
